language: python
python:
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
#  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
services:
  - postgresql
env:
  global:
    - SB_TEST_PGPORT=5432
script:
  - make test-travis
