language: python
python:
  - "3.6"  # 3.6 development branch
  - "3.7"  # 3.7 development branch
  - "3.8"

# command to install dependencies
jobs:
  include:
  - name: "Minimum install_requires versions"
    install:
      - pip install -r requirements-test.txt
      - pip install . numpy~=1.12.0 pandas~=0.24.0 SQLAlchemy~=1.1.18 psycopg2~=2.7.0
  - name: "2019-late dependencies"
    install:
      - pip install -r requirements-test.txt
      - pip install . numpy==1.17.4 pandas==0.24.2 SQLAlchemy==1.2.19 psycopg2==2.8.4
  - name: "2020-early dependencies"
    install:
      - pip install -r requirements-test.txt
      - pip install . numpy==1.17.4 pandas~=0.25.3 SQLAlchemy~=1.3.11 psycopg2~=2.8.4
  - name: "2020-mid dependencies"
    install:
      - pip install -r requirements-test.txt
      - pip install . numpy~=1.19.1 pandas~=1.1.0 SQLAlchemy~=1.3.18 psycopg2~=2.8.5
  - name: "Pure setup.py install"
    if: branch = latest
    install:
      - pip install -r requirements-test.txt
      - pip install ./
      - pip install psycopg2~=2.8.4

  # deploy on github release
  - stage: deploy
    before_deploy:
      - python3 -c 'import os, siuba; assert(os.environ["TRAVIS_TAG"] == "v" + siuba.__version__)'
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: "OGtU1RgAksy0oGmI94bgZ3e7Fkxlxjs94hBm667cAj9MIs5z1qGd32D5Se+HYsWW4Z3OYx170hSgk/AzG8MrXK41rvFoeNEd5NnZ0vY7FaLpsRErWoG/JauBiEt/Q4ize9X+2RSTgWyrKLgTccRKIKwOsO5Qyr6XJorEvJY4fdS19YZGu8sHyphFNCXeDHxZnE5EVJ71/36uv61IGh/KbMm46vZu1Adnh6UJTOkzDAkK2y1aO1Bm2kETM5EmTIVa++m63qPzU3pbcIpBC8ivz/hDIujF4wyCBpEl3M80at/GDuQjPgLkCsNC7lU5q3+f6KucND6tVBQiCVf07lpEAkGFltZrAo86i8fL9OzkFQrQY4MzCuk8ImZT+5fBoG/D7QXdyFeroAmuRSqX7/vKm3ceGFXMsP8dR2fTXWmAAEhpj3zG3/Hsck97/90PvQTd+fvMnpHqdrvRTFC6Dau1FKntRtW0qkjg+mFqGlMdy1PYCRLc7pXE3kAHwzJKEDOZnLYJC2TYniz5KUPfPtKrQhfu/55XOCC1C20v3ouJD9MeaHwla5pbEWVescXJa2nSOX6ANJYRTPiXJgnEgaBTlOFWwDNBqU1io5jgF63ai8nueacz1lXWc91VfbdZx1gLTgtHUF2/nVRA+zq+MDFAYrxG5CK45gB03hZ/3sNCxKc="
      distributions: sdist bdist_wheel
      on:
        tags: true

# command to run tests
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .
services:
  - postgresql
env:
  global:
    - SB_TEST_PGPORT=5432
script:
  - make test-travis

